### ISSUE TITLE
Compatibility with Capacitor 5

### ISSUE THREAD

**Issue by adnbrownie** [capacitor-community/photoviewer#41] opened 2023-05-11 12:42 UTC
**Describe the bug**
The plugin has configured source & target compatibility with JDK 11 (https://github.com/capacitor-community/photoviewer/blob/main/android/build.gradle#L45) as well as kotlinOptions with jvmTarget 17 (https://github.com/capacitor-community/photoviewer/blob/main/android/build.gradle#L49). Capacitor 5 requires AGP 8, which has JDK 17 as a prerequisite.

**To Reproduce**
Install the plugin in an app with capacitor 5 (or upgrade an existing project with the plugin to capacitor 5).

**Expected behavior**
Installation should work as expected. Either by no longer specifying the source & target compatibility within the plugin or by changing to JDK 17.

**Additional context**
Additionally, the package name should be moved from the `AndroidManifest.xml` file to `build.gradle` in the `android` DSL with `namespace` (though some capacitor 5 auto-magically does this with a migration script for plugins which have not already done it themselves). This is a breaking change with AGP 8. And the peer dependencies should be updated to signal compatibility with capacitor 5.

**Comment by jepiqueau** [comment] 2023-05-11 13:54
@adnbrownie it has not been converted yet to Capacitor5

**Comment by anthonyplews** [comment] 2023-05-15 17:58
When is the conversion to Capacitor 5 scheduled to happen?

**Comment by jepiqueau** [comment] 2023-05-16 07:21
@anthonyplews @adnbrownie You have a beta version published under the tag `next` can you please test it and revert to me in case of issues or success.

**Comment by anthonyplews** [comment] 2023-05-17 02:13
@jepiqueau I can confirm that it works on both Android and iOS, thanks for the quick response.

**Comment by jepiqueau** [comment] 2023-05-17 05:46
@anthonyplews thanks for your feedback i will publish it soon as the latest release

**Comment by jcesarmobile** [comment] 2023-07-20 10:24
closing since version 3.0.0 of the plugin was released with Capacitor 5 support

**Closed by jcesarmobile** 2023-07-20 10:24 UTC
