### ISSUE TITLE
Closing image by swiping up/down

### ISSUE THREAD

**Issue by michaelkhabarov** [capacitor-community/photoviewer#26] opened 2022-10-06 16:09 UTC
Hello. I can not find an ability to close an image by swiping down or up like in native apps or many js lightbox galleries. Is this possible?

**Comment by michaelkhabarov** [comment] 2022-10-06 16:39
Also when I try to swipe up or down all controls disappears and the gallery stops working until 
the back button is pressed. I am trying an Angular example app

https://user-images.githubusercontent.com/1417956/194368836-f2a24c51-ba41-454b-8383-2f366323ac0d.mov

**Comment by jepiqueau** [comment] 2022-10-07 16:34
@michaelkhabarov swiping up and down is not supported gestures. When you swipe up or down is equivalent to a tap gesture so you go into the zoom mode this is why the controls are hidden. All this is normal behaviour.  This is not a bug

**Comment by jepiqueau** [comment] 2022-10-18 05:53
@michaelkhabarov keep it open i will have a look when i have time tell me what you will expect as behaviour for swipe-up an down

**Comment by Elardzhi** [comment] 2022-11-01 15:52
I think swipe-down should be equivalent to the "Close" buton

**Comment by michaelkhabarov** [comment] 2022-11-01 20:21
In my opinion this gallery is a very nice example of swiping behaviour https://photoswipe.com

**Comment by jepiqueau** [comment] 2022-11-02 06:36
@michaelkhabarov thanks for the reference to https://photoswipe.com i saw the gesture behaviour and i think it is pretty simple. It could be implemented in the plugin but required a complete review of the code. I will see what i can do when i back home (3weeks time from now).

**Comment by jayruben** [comment] 2022-11-21 13:34
That would be pretty awesome .. I have implemented this plugin anyway. Can't wait until it's merged 🤗

**Comment by jepiqueau** [comment] 2022-11-21 18:16
@jayruben you could have made a PR and i will have merge it.

**Comment by jepiqueau** [comment] 2022-12-05 21:55
@michaelkhabarov @Elardzhi @jayruben this is fixed in 2.0.7

**Comment by jepiqueau** [comment] 2022-12-06 18:15
@michaelkhabarov @Elardzhi @jayruben  2.08 fix some issues for the web plugin

**Closed by jepiqueau** 2022-12-06 18:15 UTC

**Comment by jayruben** [comment] 2023-01-09 15:12
@jepiqueau do you have an example of the gesture? Because when I swipe to top or bottom the view will be inserted from the right if that is the effects you had implemented? Rather then the reference.. although it is nice

**Comment by jepiqueau** [comment] 2023-01-09 15:53
@jayruben on which platform ? I tried to implement what was suggested.

**Comment by jayruben** [comment] 2023-01-10 16:26
https://user-images.githubusercontent.com/16322433/211606797-0b792954-125c-4306-9d30-660a0f0b9feb.mov

@jepiqueau here is an example of how it is at my side

**Comment by jepiqueau** [comment] 2023-01-11 08:44
@jayruben this is due to the transition applied see `Extensions/UIViewController.swift` method `dismissWithTransition()` 
```
transition.subtype = CATransitionSubtype.fromRight
```
if you do not like the transition applied i can remove it so open a new issue to remove the transition
you can test on your side by
in OneImageViewController.swift comment line 217 and uncomment  line 218
in SliderViewController.swift comment line 419 an add a line self.dismiss(animated: true, completion: nil)
in SliderViewController.swift comment line 347 an add a line self.dismiss(animated: true, completion: nil)

Hope this help

**Comment by jepiqueau** [comment] 2023-01-17 08:54
@jayruben you did not come back do you want me to remove the transition

**Comment by jayruben** [comment] 2023-01-17 10:21
@jepiqueau of course you don't have to remove it, have implemented it in our app. thanks in advance

**Comment by jepiqueau** [comment] 2023-01-18 06:36
@jayruben Would you like to have an option to select the transition top, bottom, left, right ?

**Comment by jayruben** [comment] 2023-01-18 07:52
That would be awesome. 
Is there also a possibility to build in not only have the transition going from a direction but also only opacity transition with parent view controller underlying at normal position.
Or even if possible a combination of both?

Example: Direction Left + opacity
Example: Direction None + opacity
Example: Direction Bottom + No opacity

Thanks in advance,
Jay

**Comment by jepiqueau** [comment] 2023-01-18 10:23
@jayruben you mean fade in fade out. I will have a look but it is quite à job so it will take some time
